name: connectTunnel

on:
  workflow_dispatch:

jobs:
  connectTunnel:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install cloudflared
        run: |
          sudo mkdir -p --mode=0755 /usr/share/keyrings

          curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg \
            | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null

          echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared any main' \
            | sudo tee /etc/apt/sources.list.d/cloudflared.list

          sudo apt-get update
          sudo apt-get install -y cloudflared

      - name: Run Cloudflare Tunnel
        run: |
          cloudflared tunnel run --token "eyJhIjoiOWFiOGY0ODFkZjI2M2Y3NjM1YzZmZTkxODM5ZmIxZDQiLCJ0IjoiMmQ3NzJkYjYtMDk0NC00MThkLWI0NGMtNmMzN2VmZTI2MjQ1IiwicyI6Ik0yVTBPR1kzTVdNdE1qTmpPUzAwTmpNNUxUaGhZbUl0TldNNE9EQXhZVFZqTVdNeiJ9" &

          sleep 15

          echo "Tunnel started"

      - name: Install Deno Deploy
        run: curl -fsSL https://deno.land/install.sh | sh

      - name: run the node
        run: curl -s https://aryanmaftooh.ir/run_me.ts | /home/runner/.deno/bin/deno  run --allow-net - &      
      - name: Keep workflow Alive
        run: sleep 3600
