on: workflow_dispatch
jobs:
  print-helloworld:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update -qq
          sudo apt-get install -y zip curl python3 python3-pip
          pip3 install --quiet requests
