name: tor_install

on: workflow_dispatch

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Install Tor
        run: |
          sudo apt-get update
          sudo apt-get install -y tor
      - name: Start tor
        run: |
          sudo systemctl start tor
          sleep 10
      - name: Verify Tor
        run: |
          tor --version
        
          
    
